//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ClassLib
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DataEntities object using the connection string found in the 'DataEntities' section of the application configuration file.
        /// </summary>
        public DataEntities() : base("name=DataEntities", "DataEntities")

        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataEntities object.
        /// </summary>
        public DataEntities(string connectionString) : base(connectionString, "DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataEntities object.
        /// </summary>
        public DataEntities(EntityConnection connection) : base(connection, "DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Proxy> Proxies
        {
            get
            {
                if ((_Proxies == null))
                {
                    _Proxies = base.CreateObjectSet<Proxy>("Proxies");
                }
                return _Proxies;
            }
        }
        private ObjectSet<Proxy> _Proxies;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Proxies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProxies(Proxy proxy)
        {
            base.AddObject("Proxies", proxy);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="Proxy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Proxy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Proxy object.
        /// </summary>
        /// <param name="proxyId">Initial value of the ProxyId property.</param>
        public static Proxy CreateProxy(global::System.Int32 proxyId)
        {
            Proxy proxy = new Proxy();
            proxy.ProxyId = proxyId;
            return proxy;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProxyName
        {
            get
            {
                return _ProxyName;
            }
            set
            {
                OnProxyNameChanging(value);
                ReportPropertyChanging("ProxyName");
                _ProxyName = StructuralObject.SetValidValue(value, true, "ProxyName");
                ReportPropertyChanged("ProxyName");
                OnProxyNameChanged();
            }
        }
        private global::System.String _ProxyName;
        partial void OnProxyNameChanging(global::System.String value);
        partial void OnProxyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProxyAddres
        {
            get
            {
                return _ProxyAddres;
            }
            set
            {
                OnProxyAddresChanging(value);
                ReportPropertyChanging("ProxyAddres");
                _ProxyAddres = StructuralObject.SetValidValue(value, true, "ProxyAddres");
                ReportPropertyChanged("ProxyAddres");
                OnProxyAddresChanged();
            }
        }
        private global::System.String _ProxyAddres;
        partial void OnProxyAddresChanging(global::System.String value);
        partial void OnProxyAddresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProxyPort
        {
            get
            {
                return _ProxyPort;
            }
            set
            {
                OnProxyPortChanging(value);
                ReportPropertyChanging("ProxyPort");
                _ProxyPort = StructuralObject.SetValidValue(value, "ProxyPort");
                ReportPropertyChanged("ProxyPort");
                OnProxyPortChanged();
            }
        }
        private Nullable<global::System.Int32> _ProxyPort;
        partial void OnProxyPortChanging(Nullable<global::System.Int32> value);
        partial void OnProxyPortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProxyUsername
        {
            get
            {
                return _ProxyUsername;
            }
            set
            {
                OnProxyUsernameChanging(value);
                ReportPropertyChanging("ProxyUsername");
                _ProxyUsername = StructuralObject.SetValidValue(value, true, "ProxyUsername");
                ReportPropertyChanged("ProxyUsername");
                OnProxyUsernameChanged();
            }
        }
        private global::System.String _ProxyUsername;
        partial void OnProxyUsernameChanging(global::System.String value);
        partial void OnProxyUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProxyPassword
        {
            get
            {
                return _ProxyPassword;
            }
            set
            {
                OnProxyPasswordChanging(value);
                ReportPropertyChanging("ProxyPassword");
                _ProxyPassword = StructuralObject.SetValidValue(value, true, "ProxyPassword");
                ReportPropertyChanged("ProxyPassword");
                OnProxyPasswordChanged();
            }
        }
        private global::System.String _ProxyPassword;
        partial void OnProxyPasswordChanging(global::System.String value);
        partial void OnProxyPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value, "DateCreated");
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProxyId
        {
            get
            {
                return _ProxyId;
            }
            set
            {
                if (_ProxyId != value)
                {
                    OnProxyIdChanging(value);
                    ReportPropertyChanging("ProxyId");
                    _ProxyId = StructuralObject.SetValidValue(value, "ProxyId");
                    ReportPropertyChanged("ProxyId");
                    OnProxyIdChanged();
                }
            }
        }
        private global::System.Int32 _ProxyId;
        partial void OnProxyIdChanging(global::System.Int32 value);
        partial void OnProxyIdChanged();

        #endregion

    }

    #endregion

}
