//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TwitterAtomationWa
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DataEntities object using the connection string found in the 'DataEntities' section of the application configuration file.
        /// </summary>
        public DataEntities() : base("name=DataEntities", "DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataEntities object.
        /// </summary>
        public DataEntities(string connectionString) : base(connectionString, "DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataEntities object.
        /// </summary>
        public DataEntities(EntityConnection connection) : base(connection, "DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Proxy> Proxies
        {
            get
            {
                if ((_Proxies == null))
                {
                    _Proxies = base.CreateObjectSet<Proxy>("Proxies");
                }
                return _Proxies;
            }
        }
        private ObjectSet<Proxy> _Proxies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Account> Accounts
        {
            get
            {
                if ((_Accounts == null))
                {
                    _Accounts = base.CreateObjectSet<Account>("Accounts");
                }
                return _Accounts;
            }
        }
        private ObjectSet<Account> _Accounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message> Messages
        {
            get
            {
                if ((_Messages == null))
                {
                    _Messages = base.CreateObjectSet<Message>("Messages");
                }
                return _Messages;
            }
        }
        private ObjectSet<Message> _Messages;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Proxies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProxies(Proxy proxy)
        {
            base.AddObject("Proxies", proxy);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccounts(Account account)
        {
            base.AddObject("Accounts", account);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Messages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessages(Message message)
        {
            base.AddObject("Messages", message);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="Account")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Account : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Account object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Account CreateAccount(global::System.Int32 id)
        {
            Account account = new Account();
            account.id = id;
            return account;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ScreenName
        {
            get
            {
                return _ScreenName;
            }
            set
            {
                OnScreenNameChanging(value);
                ReportPropertyChanging("ScreenName");
                _ScreenName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ScreenName");
                OnScreenNameChanged();
            }
        }
        private global::System.String _ScreenName;
        partial void OnScreenNameChanging(global::System.String value);
        partial void OnScreenNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Token
        {
            get
            {
                return _Token;
            }
            set
            {
                OnTokenChanging(value);
                ReportPropertyChanging("Token");
                _Token = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Token");
                OnTokenChanged();
            }
        }
        private global::System.String _Token;
        partial void OnTokenChanging(global::System.String value);
        partial void OnTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TokenSecret
        {
            get
            {
                return _TokenSecret;
            }
            set
            {
                OnTokenSecretChanging(value);
                ReportPropertyChanging("TokenSecret");
                _TokenSecret = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TokenSecret");
                OnTokenSecretChanged();
            }
        }
        private global::System.String _TokenSecret;
        partial void OnTokenSecretChanging(global::System.String value);
        partial void OnTokenSecretChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProxyAddress
        {
            get
            {
                return _ProxyAddress;
            }
            set
            {
                OnProxyAddressChanging(value);
                ReportPropertyChanging("ProxyAddress");
                _ProxyAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProxyAddress");
                OnProxyAddressChanged();
            }
        }
        private global::System.String _ProxyAddress;
        partial void OnProxyAddressChanging(global::System.String value);
        partial void OnProxyAddressChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="Message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Message CreateMessage(global::System.Int32 id)
        {
            Message message = new Message();
            message.id = id;
            return message;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message1
        {
            get
            {
                return _Message1;
            }
            set
            {
                OnMessage1Changing(value);
                ReportPropertyChanging("Message1");
                _Message1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message1");
                OnMessage1Changed();
            }
        }
        private global::System.String _Message1;
        partial void OnMessage1Changing(global::System.String value);
        partial void OnMessage1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProxyID
        {
            get
            {
                return _ProxyID;
            }
            set
            {
                OnProxyIDChanging(value);
                ReportPropertyChanging("ProxyID");
                _ProxyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProxyID");
                OnProxyIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ProxyID;
        partial void OnProxyIDChanging(Nullable<global::System.Int32> value);
        partial void OnProxyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private Nullable<global::System.Int32> _Priority;
        partial void OnPriorityChanging(Nullable<global::System.Int32> value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateSended
        {
            get
            {
                return _DateSended;
            }
            set
            {
                OnDateSendedChanging(value);
                ReportPropertyChanging("DateSended");
                _DateSended = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateSended");
                OnDateSendedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateSended;
        partial void OnDateSendedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateSendedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rScreenName
        {
            get
            {
                return _rScreenName;
            }
            set
            {
                OnrScreenNameChanging(value);
                ReportPropertyChanging("rScreenName");
                _rScreenName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rScreenName");
                OnrScreenNameChanged();
            }
        }
        private global::System.String _rScreenName;
        partial void OnrScreenNameChanging(global::System.String value);
        partial void OnrScreenNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> rUserID
        {
            get
            {
                return _rUserID;
            }
            set
            {
                OnrUserIDChanging(value);
                ReportPropertyChanging("rUserID");
                _rUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rUserID");
                OnrUserIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _rUserID;
        partial void OnrUserIDChanging(Nullable<global::System.Decimal> value);
        partial void OnrUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> nextTryDate
        {
            get
            {
                return _nextTryDate;
            }
            set
            {
                OnnextTryDateChanging(value);
                ReportPropertyChanging("nextTryDate");
                _nextTryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nextTryDate");
                OnnextTryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _nextTryDate;
        partial void OnnextTryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnnextTryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SenderscreenName
        {
            get
            {
                return _SenderscreenName;
            }
            set
            {
                OnSenderscreenNameChanging(value);
                ReportPropertyChanging("SenderscreenName");
                _SenderscreenName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SenderscreenName");
                OnSenderscreenNameChanged();
            }
        }
        private global::System.String _SenderscreenName;
        partial void OnSenderscreenNameChanging(global::System.String value);
        partial void OnSenderscreenNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="Proxy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Proxy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Proxy object.
        /// </summary>
        /// <param name="proxyId">Initial value of the ProxyId property.</param>
        public static Proxy CreateProxy(global::System.Int32 proxyId)
        {
            Proxy proxy = new Proxy();
            proxy.ProxyId = proxyId;
            return proxy;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProxyName
        {
            get
            {
                return _ProxyName;
            }
            set
            {
                OnProxyNameChanging(value);
                ReportPropertyChanging("ProxyName");
                _ProxyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProxyName");
                OnProxyNameChanged();
            }
        }
        private global::System.String _ProxyName;
        partial void OnProxyNameChanging(global::System.String value);
        partial void OnProxyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProxyAddres
        {
            get
            {
                return _ProxyAddres;
            }
            set
            {
                OnProxyAddresChanging(value);
                ReportPropertyChanging("ProxyAddres");
                _ProxyAddres = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProxyAddres");
                OnProxyAddresChanged();
            }
        }
        private global::System.String _ProxyAddres;
        partial void OnProxyAddresChanging(global::System.String value);
        partial void OnProxyAddresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProxyPort
        {
            get
            {
                return _ProxyPort;
            }
            set
            {
                OnProxyPortChanging(value);
                ReportPropertyChanging("ProxyPort");
                _ProxyPort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProxyPort");
                OnProxyPortChanged();
            }
        }
        private Nullable<global::System.Int32> _ProxyPort;
        partial void OnProxyPortChanging(Nullable<global::System.Int32> value);
        partial void OnProxyPortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProxyUsername
        {
            get
            {
                return _ProxyUsername;
            }
            set
            {
                OnProxyUsernameChanging(value);
                ReportPropertyChanging("ProxyUsername");
                _ProxyUsername = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProxyUsername");
                OnProxyUsernameChanged();
            }
        }
        private global::System.String _ProxyUsername;
        partial void OnProxyUsernameChanging(global::System.String value);
        partial void OnProxyUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProxyPassword
        {
            get
            {
                return _ProxyPassword;
            }
            set
            {
                OnProxyPasswordChanging(value);
                ReportPropertyChanging("ProxyPassword");
                _ProxyPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProxyPassword");
                OnProxyPasswordChanged();
            }
        }
        private global::System.String _ProxyPassword;
        partial void OnProxyPasswordChanging(global::System.String value);
        partial void OnProxyPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProxyId
        {
            get
            {
                return _ProxyId;
            }
            set
            {
                if (_ProxyId != value)
                {
                    OnProxyIdChanging(value);
                    ReportPropertyChanging("ProxyId");
                    _ProxyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProxyId");
                    OnProxyIdChanged();
                }
            }
        }
        private global::System.Int32 _ProxyId;
        partial void OnProxyIdChanging(global::System.Int32 value);
        partial void OnProxyIdChanged();

        #endregion

    
    }

    #endregion

    
}
